### PR TITLE
set_timeout, GitHub tree links, paths and more!

### LINKED ISSUE #136: feat: support data urls in images
img tags should support base64 encoded images in data urls

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

### PR DESCRIPTION
**Pull request by GStudiosX2**
* add set_timeout lua function (#108)
* add clear_timeout lua function
* add set_visible lua function 
* github tree links should work (eg: https://github.com/GStudiosX2/random-now/tree/test)
* allow for path in urls (eg: random.now/test)
* sandbox lua (NEEDS TESTING #108 )
* allow nil in set_content
* base64 images (closes #136)

### CODE REVIEW

**Review by Sakura-sx — COMMENTED** [review]
Haven't tested yet but looks promising.

**Comment by GStudiosX2** [comment]
https://github.com/face-hh/webx/assets/76548041/67b9e99d-e145-48f4-8969-486c933ae0f0

Someone made videos with this pr lol
Credit: thebroz on discord

**Comment by jabinstech** [comment]
this would be good

**Comment by GStudiosX2** [comment]
The only thing I tested it on is Dingle &  on the set_timeout example I added

**Comment by the-broz** [comment]
set_timeout seems to use memory and cpu even after closing the website using it. might need to check that.

**Comment by GStudiosX2** [comment]
> set_timeout seems to use memory and cpu even after closing the website using it. might need to check that.

Yeah it's a just a simple implementation probably want to store the timeout some where and then abort them all when switching pages

**Comment by GStudiosX2** [comment]
Last for real now

**Comment by GStudiosX2** [comment]
In process of fixing conflicts

**Comment by GStudiosX2** [comment]
> f89xFqz.mp4 
> Someone made videos with this pr lol Credit: thebroz on discord

https://github.com/face-hh/webx/assets/76548041/0da6d1b7-af51-470b-838b-918f4107a6d9

**Comment by goodzombz** [comment]
this is fire and you are a legend

**Comment by GStudiosX2** [comment]
Someone made actual video support #150

**Comment by face-hh** [comment]
This part is breaking local paths.
```rs
async fn parse_html(mut url: String) -> Result<(Node, Node)> {
    println!("{url}"); // file://C:\Users\Face\Documents\GitHub\webx_github\napture\test
    if let Ok(mut uri) = Url::parse(&url) {
       if let Ok(mut segments) = uri.path_segments_mut() {
           segments.pop_if_empty();
           segments.push("index.html");
       }
       url = uri.into();
    }

    println!("{url}"); // /C:/Users/Face/Documents/GitHub/webx_github/napture/test/index.html

    let html = fetch_file(url).await;
```

**Comment by GStudiosX2** [comment]
Ohhh ok I'll see if I can fix it

**Comment by GStudiosX2** [comment]
Can you test I haven't checked if it compiles lol

**Comment by GStudiosX2** [comment]
@face-hh

**Comment by face-hh** [comment]
image
same issue

**Comment by face-hh** [comment]
The DNS doesn't seem to work on this pull request

**Comment by face-hh** [comment]
> The DNS doesn't seem to work on this pull request

Nevermind, it was my DNS setting

**Comment by face-hh** [comment]
Everything else seems to work fine

**Comment by GStudiosX2** [comment]
> image same issue

Your not meant to put file:/// on windows it's file:// the fix you added makes it break on Linux now

**Pull request merged**
