### PR TITLE
Added install script

### PR DESCRIPTION
**Pull request by Smartlinuxcoder**
I found the bug that made the app impossible to open, and made an automated script to "apply the fix" and install napture as an application

### CODE REVIEW

**Comment by JustDoom** [comment]
I tried it but I just get


```
Installing Napture...
    Finished release [optimized] target(s) in 0.10s
No schema files found: doing nothing.
Napture installation completed.

```

**Comment by Smartlinuxcoder** [comment]
> I tried it but I just get
> 
> 
> ```
> Installing Napture...
>     Finished release [optimized] target(s) in 0.10s
> No schema files found: doing nothing.
> Napture installation completed.
> 
> ```

Which os are you using?

**Comment by JustDoom** [comment]
@Smartlinuxcoder I am using Kubuntu 24

**Comment by JustDoom** [comment]
I tried it on my PC and I think it worked. Get a window popping up but crashes when I try go to `buss://yippie.rizz` which I don't think is an issue with this

**Comment by face-hh** [comment]
> I tried it on my PC and I think it worked. Get a window popping up but crashes when I try go to `buss://yippie.rizz` which I don't think is an issue with this

Try running it from the command line, it should print the reason for the crash

**Comment by JustDoom** [comment]
for my laptop it says
```
./napture/target/release/webx 

(.:4593): Gtk-WARNING **: 18:46:40.619: Unknown key gtk-modules in /home/doom/.config/gtk-4.0/settings.ini

(.:4593): Adwaita-WARNING **: 18:46:40.739: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(.:4593): GLib-GIO-ERROR **: 18:46:40.900: Settings schema 'org.bussin.napture' is not installed
Trace/breakpoint trap (core dumped)

```

**Pull request merged**
