### PR TITLE
Add The Git clone 

### PR DESCRIPTION
**Pull request by CooperDActor-bytes**
I was so dumb that I forgot that I had to do that
I am 12 give me a break (kitkat)

### CODE REVIEW

**Comment by CooperDActor-bytes** [comment]
please make me the bussing spokes person

**Review by ZakaHaceCosas — APPROVED** [review]
Added to #181 (as that PR makes many changes to README, I think it's better to have it all on the same PR).

**Comment by TheZitroX** [comment]
wtf.

**Comment by TheZitroX** [comment]
"studying at Nguyễn Tri Phương Junior Highschool!"
why is a 12y'old here on github?

**Comment by CooperDActor-bytes** [comment]
oh thats not me 
although I am 12 I am Australian he is veitnimeese 

also the kids are coming for your jobs

**Comment by CooperDActor-bytes** [comment]
hey zaka you are a maintainer or not?
coz you shouldn't be able to just take someones work and add it to your own 
thats if you are not

**Comment by CooperDActor-bytes** [comment]
also you should have (when edited your commits) add my username at least

**Comment by CooperDActor-bytes** [comment]
> "studying at Nguyễn Tri Phương Junior Highschool!" why is a 12y'old here on github?

because I am better :_-) thats a tear face

**Comment by TheZitroX** [comment]
I don't get this

**Comment by CooperDActor-bytes** [comment]
> I don't get this

get what?

**Comment by TheZitroX** [comment]
Yes

**Pull request closed without merging**
