### PR TITLE
Created a propper documentation

### PR DESCRIPTION
**Pull request by ZakaHaceCosas**
Full documentation for Bussin WebX. It's made in VitePress (with TS and custom CSS enabled).

Content:
- User manual
- Developer manual
- API reference
- List of available browsers.
- List of available domain providers.

Everything is up to date for engine version 1.2.2. As new versions release I'll try to keep this up to date.

Notes:
- A few pages need reviewing (Luau manual needs reviewing at the `SET` section, Site publishing needs reviewing at the `Getting my domain` section, and Advanced options needs reviewing at the `Using other browsers` section).
- I took the freedom to call our CSS 3 improvement "CSS 3.25", to accompany HTML ++. _Take it or leave it._

If any change or update is required just tell me and I'll take care hapily 👍.

### CODE REVIEW

**Comment by inventionpro** [comment]
Looks good, thing is we already have a gitbook docs page, if anything better updating that than creating another thing to host

**Comment by ZakaHaceCosas** [comment]
The GitBook is not open source I think?

**Comment by inventionpro** [comment]
you can ask face to give you access

**Comment by ZakaHaceCosas** [comment]
That's algo an option, I could take care of the docs... but isn't it easier to merge this PR and make the docs open source? It would make it easier to maintain and to keep up to date

**Comment by inventionpro** [comment]
good point

**Comment by GStudiosX2** [comment]
Looking through this right now I found one mistake ```
> You cannot embed <style> tags or write inline scripts in your HTML. Due to that, the script tag must be self closing, even **thought** your IDE might mark that as an error.
so far (thought should be though maybe both make sense though)

**Comment by GStudiosX2** [comment]
> Additionally, as of B9 v1.2.2 images are currently broken on Microsoft Windows&tm; and will only work if you follow the Guide of Compilation for Napture - Windows..

&tm;

**Comment by ZakaHaceCosas** [comment]
Noted. Tomorrow will fix that and give it a full review just in case there are any other typos. Thanks.

**Comment by GStudiosX2** [comment]
You should also note that font-height is actually in pt

**Comment by GStudiosX2** [comment]
Oh and #121 is merged now so you probably can document more about set_visible (but maybe could wait till it's in a release version)

**Comment by ZakaHaceCosas** [comment]
> Oh and #121 is merged now so you probably can document more about set_visible (but maybe could wait till it's in a release version) and theres also set_timeout and clear_timeout

Sure, I'll take a look at it when I get home.

**Comment by ZakaHaceCosas** [comment]
Thanks! Will start working on that as soon as I get home.

**Comment by ZakaHaceCosas** [comment]
# UPDATE
- Port to `GitBook` from `VitePress` **done**
- Fixing typos **done**
- Updating the Luau reference and finishing it **done**
- PLUS Small tweaks and improvments

If any other update is needed just tell me. Now this should be up to date for B9 / Napture 1.2.2. (When there's a new release I'll try to keep the docs up to date ASAP).

**Comment by ZakaHaceCosas** [comment]
(fixed the fact i forgor to remove the old vitepress, lol). now it's fine.

**Comment by ZakaHaceCosas** [comment]
Updated API Reference

**Comment by face-hh** [comment]
I'll merge this and polish it via Gitbook since it has no way of testing pull requests :^)

**Pull request merged**
