### PR TITLE
Move and modularize the install scripts

### PR DESCRIPTION
**Pull request by QuinceTart10**
I think everything is clear from the commits + idk how to describe this

### CODE REVIEW

**Comment by QuinceTart10** [comment]
@Helloyunho could you test out the modified macOS script please? I need to know that it still works.

**Comment by Helloyunho** [comment]
@QuinceTart10 It works fine, but I think I forgot to first remove the old Napture installation and then move the new one

```sh
# For example
rm -rf /Applications/Napture.app || true # ignore fails
mv target/release/Napture.app /Applications || exit 1
```

Can you do that for me? (or if there's a flag in `mv` that does this automatically you can use that as well)

**Comment by Helloyunho** [comment]
@QuinceTart10 you missed `|| true` part which is important since it will raise error when the app is not already installed

**Comment by QuinceTart10** [comment]
> @QuinceTart10 you missed `|| true` part which is important since it will raise error when the app is not already installed

Ah, sorry. Let me do it real quick.

**Comment by ByzantineProcess** [comment]
image
works!

**Pull request merged**
