### PR TITLE
Ported Custom DNS code from WebX-Plus Renapture

### PR DESCRIPTION
**Pull request by TheGreatJaeger**
The code used in the WebX-Plus version of Napture ported to the original source

### CODE REVIEW

**Comment by ByzantineProcess** [comment]
I like how this is persistent, might be able to merge this and my PR #110 together for best of both worlds

**Comment by face-hh** [comment]
This saves to file system so it won't work on built executables

**Comment by lifeisfakenews** [comment]
how do other apps store stuff in files then

**Comment by face-hh** [comment]
Will be implemented in #110

**Comment by face-hh** [comment]
> how do other apps store stuff in files then

appdata

**Pull request closed without merging**
