### PR TITLE
draft: build UI for website in thread

### LINKED ISSUE #198: FEATURE: Move Lua out of the main thread
**Is your feature request related to a problem? Please describe.**
The UI of the entire browser should not freeze when a Web X® site decides to run a while true do loop or crash the client in any way.

**Describe the solution you'd like**
Separate the Web X® site's code and UI from Napture's main thread.

### PR DESCRIPTION
**Pull request by RealPacket**
TODO:
- [X] Move b9::html::build_ui call in handle_search_update into thread
- [ ] Move Web X® site code into thread
- [ ] Put tape on Rust's mouth and make it shut up so that the code compiles.

Fixes #198

### CODE REVIEW

**Comment by GStudiosX2** [comment]
GTK4 is not thread safe do not do this

**Comment by RealPacket** [comment]
> Most of GTK4 is not thread safe do not try to do this it may not work well you'll still have to do a lot of GTK stuff on the main thread
> 
> Edit: though I haven't really took at look at your code yet I just read the title Edit2: not trying to be rude or anything just trying to warn you about it may cause issues I haven't checked what actually happens

https://stackoverflow.com/questions/66510406/gtk-rs-how-to-update-view-from-another-thread

**Comment by GStudiosX2** [comment]
> > Most of GTK4 is not thread safe do not try to do this it may not work well you'll still have to do a lot of GTK stuff on the main thread
> > 
> > Edit: though I haven't really took at look at your code yet I just read the title Edit2: not trying to be rude or anything just trying to warn you about it may cause issues I haven't checked what actually happens
> 
> https://stackoverflow.com/questions/66510406/gtk-rs-how-to-update-view-from-another-thread

Ah I thought you where gonna try and update the UI in a separate thread lol

**Comment by RealPacket** [comment]
> > > Most of GTK4 is not thread safe do not try to do this it may not work well you'll still have to do a lot of GTK stuff on the main thread
> > > 
> > > Edit: though I haven't really took at look at your code yet I just read the title Edit2: not trying to be rude or anything just trying to warn you about it may cause issues I haven't checked what actually happens
> > 
> > https://stackoverflow.com/questions/66510406/gtk-rs-how-to-update-view-from-another-thread
> 
> Ah I thought you where gonna try and update the UI in the separate thread lol

Well... I'm going to need to either:
- Contribute to GTK-rs by implementing the `Send` trait for GTK Objects
- ...or modify the code for b9::html::build_ui, a lot...
Probably would rather add the `Send` trait so that I can just unwrap a `Mutex` or `RwLock` and pass them to the function.

**Comment by RealPacket** [comment]
https://github.com/search?q=repo%3Agtk-rs%2Fgtk4-rs+%22unsafe+impl+Send+for%22+language%3ARust&type=code
https://github.com/search?q=repo%3Agtk-rs%2Fgtk4-rs+%22unsafe+impl+Sync+for%22+language%3ARust&type=code
No UI object has Send or Sync implemented...

**Comment by face-hh** [comment]
You may be able to do it through channels. Check the dev branch for a basic (semi-working) implementation of running the HTML, CSS and Lua loading in parallel

**Comment by RealPacket** [comment]
I'll start working on https://github.com/RealPacket/webx/tree/dev instead in hopes of making the semi-working implementation into a working implementation.
I'd like it to not freeze (like normal browsers) too.

**Comment by RealPacket** [comment]
image
:skull: (went to cat.lol)

**Pull request closed without merging**
