### PR TITLE
Make browser not freeze when loading a page

### PR DESCRIPTION
**Pull request by Sakura-sx**
Changed fetch_dns code to be async. Haven't tested it so please test before commiting it.

### CODE REVIEW

**Review by vt-d — CHANGES_REQUESTED** [review]
Refrain from using eprintln

**Comment by Sakura-sx** [comment]
Thanks, fixing it

**Comment by Sakura-sx** [comment]
Fixed

**Comment by Sakura-sx** [comment]
Do not merge. It returns this error:

```
Compiling webx v1.2.2 (D:\workspace\webx\napture)
error[E0277]: `reqwest::ClientBuilder` is not a future
   --> src\main.rs:364:45
    |
364 |     let client = reqwest::Client::builder().await.build()
    |                  ---------------------------^^^^^
    |                  |                         ||
    |                  |                         |`reqwest::ClientBuilder` is not a future
    |                  |                         help: remove the `.await`
    |                  this call returns `reqwest::ClientBuilder`
    |
    = help: the trait `Future` is not implemented for `reqwest::ClientBuilder`, which is required by `reqwest::ClientBuilder: IntoFuture`
    = note: reqwest::ClientBuilder must be a future or must implement `IntoFuture` to be awaited
    = note: required for `reqwest::ClientBuilder` to implement `IntoFuture`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `webx` (bin "webx") due to 1 previous error
```

Further "asyncization" is needed.

**Comment by Xanderplayz16** [comment]
Can you update the name of the pull request to be descriptive, and not just "Update main.rs"?

**Comment by face-hh** [comment]
The entire logic behind the async runtime should be changed, not just the fetch_dns function

**Pull request closed without merging**
