### PR TITLE
Add bus2:// protocol (for bus2 dns)

### PR DESCRIPTION
**Pull request by Siomek101**
Host: buss.bubbleam.pl
[GET] /domain/:name/:tld <-- get domain's ip
Example response:
{
  tld: [tld],
  name: [name],
  ip: [ip]
}

[POST] /adddomain (needed in body: tld, name, ip) <-- add a domain
Example response: [SECRET / TOKEN]

[POST] /updatedomain (needed in body: tld, name, ip, secret) <-- update a domain
Example response: OK

### CODE REVIEW

**Comment by Timoh5709** [comment]
We need compatibility with more dns servers 🔥🔥

**Comment by Sakura-sx** [comment]
So now we add support for another centralized DNS, that's also proprietary? If you want to improve on the DNS, just commit the changes.

**Comment by Sakura-sx** [comment]
Adding a dns setting for custom dns servers is a great idea. That's what should be done instead of making a new protocol for every new propietary dns server.

**Comment by Siomek101** [comment]
> Adding a dns setting for custom dns servers is a great idea. That's what should be done instead of making a new protocol for every new propietary dns server.

this was the easiest solution for now

**Comment by Sakura-sx** [comment]
There is absolutely no need for this at the moment, before we should make subdomains and paths work. That's way more asked and needed than yet another DNS.

**Comment by Siomek101** [comment]
> There is absolutely no need for this at the moment, before we should make subdomains and paths work. That's way more asked and needed than yet another DNS.

if my dns is gonna be successful, im gonna implement subdomains
just not today its 23:35 now i really need some sleep

**Comment by Xanderplayz16** [comment]
I think a better solution would be if a DNS doesn't get anything, that DNS contacts another DNS in a list (maybe a config option) and sees if it has a record, if not it goes to the next DNS on the list. If it has a record for it, it returns the IP from the other DNS.

**Comment by Siomek101** [comment]
> I think a better solution would be if a DNS doesn't get anything, that DNS contacts another DNS in a list (maybe a config option) and sees if it has a record, if not it goes to the next DNS on the list. If it has a record for it, it returns the IP from the other DNS.

thats literally how DNS works, but im gonna implement it tommorow

**Comment by Xanderplayz16** [comment]
> > I think a better solution would be if a DNS doesn't get anything, that DNS contacts another DNS in a list (maybe a config option) and sees if it has a record, if not it goes to the next DNS on the list. If it has a record for it, it returns the IP from the other DNS.
> 
> would absolutely have to be a config option, probably with only the buss dns by default. only problem is what if a domain is on multiple dns's? would it grab from the first one in the list, or something else?

Instead of a list of DNS servers, a list of lists which contain a DNS server's URL, then a priority value. The higher the value, the more preferred it is over the other servers.

**Comment by face-hh** [comment]
Implemented in #110

**Pull request closed without merging**
